/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ColorSetting: typeof import('./components/ColorSetting.vue')['default']
    Contact: typeof import('./components/Contact.vue')['default']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElRow: typeof import('element-plus/es')['ElRow']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IEpAvatar: typeof import('~icons/ep/avatar')['default']
    IEpBasketball: typeof import('~icons/ep/basketball')['default']
    IEpBriefcase: typeof import('~icons/ep/briefcase')['default']
    IEpCalendar: typeof import('~icons/ep/calendar')['default']
    IEpCheck: typeof import('~icons/ep/check')['default']
    IEpCloseBold: typeof import('~icons/ep/close-bold')['default']
    IEpDocument: typeof import('~icons/ep/document')['default']
    IEpEdit: typeof import('~icons/ep/edit')['default']
    IEpFilm: typeof import('~icons/ep/film')['default']
    IEpGoodsFilled: typeof import('~icons/ep/goods-filled')['default']
    IEpNotebook: typeof import('~icons/ep/notebook')['default']
    IEpOfficeBuilding: typeof import('~icons/ep/office-building')['default']
    IEpPhone: typeof import('~icons/ep/phone')['default']
    IEpPosition: typeof import('~icons/ep/position')['default']
    IEpPromotion: typeof import('~icons/ep/promotion')['default']
    IEpSelect: typeof import('~icons/ep/select')['default']
    IEpSetUp: typeof import('~icons/ep/set-up')['default']
    IEpShare: typeof import('~icons/ep/share')['default']
    IEpStamp: typeof import('~icons/ep/stamp')['default']
    IEpStarFilled: typeof import('~icons/ep/star-filled')['default']
    IEpSuccessFilled: typeof import('~icons/ep/success-filled')['default']
    IEpTools: typeof import('~icons/ep/tools')['default']
    IEpTrophyBase: typeof import('~icons/ep/trophy-base')['default']
    IEpUserFilled: typeof import('~icons/ep/user-filled')['default']
    Me: typeof import('./components/Me.vue')['default']
    Nav: typeof import('./components/Nav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserPinia: typeof import('./components/UserPinia.vue')['default']
  }
}
